version: '3'
networks:
  geoquizz.net:
    driver: bridge
services:

#  geoquizz.parties.db:
#    image: 'mariadb:latest'
#    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
#    env_file: ./parties.env
#    ports:
#      - '3307:3306' # 40503
#    networks:
#      - geoquizz.net
#    volumes:
#      - ../parties.geoquizz/sql:/var/sql
#      - ../parties.geoquizz/sql/order:/docker-entrypoint-initdb.d
#
#  api.geoquizz:
#    image: 'canals/php:8.2'
#    env_file: ./parties.env
#    ports:
#      - '2080:80' #40501
#      - '1443:443' #40502
#    volumes:
#      - ../parties.geoquizz/public:/var/www/html
#      - ../parties.geoquizz:/var/www
#    working_dir: /var/www/
#    networks:
#      geoquizz.net:
#        aliases:
#          - api.geoquizz.local
#    depends_on:
#      - geoquizz.parties.db


  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '8081:8080' ## 40510
    networks:
      - geoquizz.net

  ######################################
  ###  AUTH Service : service d'authentification JWT
  ###  api api.auth : auth, check, refresh de token JWT
  ###  utilise sa propre base de données
  ######################################
  api.geoquizz-auth:
    image: 'canals/php:8.2'
    env_file: ./auth.env
    ports:
      - '2082:80' ## 40506
      - '1444:443' ## 40507
    volumes:
      - ../auth.geoquizz/public:/var/www/html
      - ../auth.geoquizz:/var/www
    working_dir: /var/www
    networks:
      geoquizz.net:
        aliases:
          - auth.geoquizz.local
    depends_on:
      - geoquizz.auth.db
    command: >
      bash -c "composer install && composer update && apache2-foreground"

  geoquizz.auth.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./auth.env
    ports:
      - '3309:3306' ## 40508
    networks:
      - geoquizz.net
    volumes:
      - ../auth.geoquizz/sql:/var/sql
      - ../auth.geoquizz/sql:/docker-entrypoint-initdb.d

  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ../series.geoquizz/data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.8.3
    ports:
      - 8055:8055
    volumes:
      - ../series.geoquizz/uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"


